/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Agendamentos } from "./Agendamentos";
import { AgendamentosCountArgs } from "./AgendamentosCountArgs";
import { AgendamentosFindManyArgs } from "./AgendamentosFindManyArgs";
import { AgendamentosFindUniqueArgs } from "./AgendamentosFindUniqueArgs";
import { DeleteAgendamentosArgs } from "./DeleteAgendamentosArgs";
import { AgendamentosService } from "../agendamentos.service";
@graphql.Resolver(() => Agendamentos)
export class AgendamentosResolverBase {
  constructor(protected readonly service: AgendamentosService) {}

  async _agendamentosItemsMeta(
    @graphql.Args() args: AgendamentosCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Agendamentos])
  async agendamentosItems(
    @graphql.Args() args: AgendamentosFindManyArgs
  ): Promise<Agendamentos[]> {
    return this.service.agendamentosItems(args);
  }

  @graphql.Query(() => Agendamentos, { nullable: true })
  async agendamentos(
    @graphql.Args() args: AgendamentosFindUniqueArgs
  ): Promise<Agendamentos | null> {
    const result = await this.service.agendamentos(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Agendamentos)
  async deleteAgendamentos(
    @graphql.Args() args: DeleteAgendamentosArgs
  ): Promise<Agendamentos | null> {
    try {
      return await this.service.deleteAgendamentos(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
