/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AgendamentosListRelationFilter } from "../../agendamentos/base/AgendamentosListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { TransacoesListRelationFilter } from "../../transacoes/base/TransacoesListRelationFilter";

@InputType()
class ClientesWhereInput {
  @ApiProperty({
    required: false,
    type: () => AgendamentosListRelationFilter,
  })
  @ValidateNested()
  @Type(() => AgendamentosListRelationFilter)
  @IsOptional()
  @Field(() => AgendamentosListRelationFilter, {
    nullable: true,
  })
  agendamentosItems?: AgendamentosListRelationFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  dataNascimento?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  email?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  nome?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  telefone?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => TransacoesListRelationFilter,
  })
  @ValidateNested()
  @Type(() => TransacoesListRelationFilter)
  @IsOptional()
  @Field(() => TransacoesListRelationFilter, {
    nullable: true,
  })
  transacoesItems?: TransacoesListRelationFilter;
}

export { ClientesWhereInput as ClientesWhereInput };
