/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { FuncionariosService } from "../funcionarios.service";
import { FuncionariosCreateInput } from "./FuncionariosCreateInput";
import { Funcionarios } from "./Funcionarios";
import { FuncionariosFindManyArgs } from "./FuncionariosFindManyArgs";
import { FuncionariosWhereUniqueInput } from "./FuncionariosWhereUniqueInput";
import { FuncionariosUpdateInput } from "./FuncionariosUpdateInput";
import { AcessosFindManyArgs } from "../../acessos/base/AcessosFindManyArgs";
import { Acessos } from "../../acessos/base/Acessos";
import { AcessosWhereUniqueInput } from "../../acessos/base/AcessosWhereUniqueInput";

export class FuncionariosControllerBase {
  constructor(protected readonly service: FuncionariosService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Funcionarios })
  async createFuncionarios(
    @common.Body() data: FuncionariosCreateInput
  ): Promise<Funcionarios> {
    return await this.service.createFuncionarios({
      data: data,
      select: {
        cargo: true,
        createdAt: true,
        email: true,
        id: true,
        nome: true,
        salario: true,
        telefone: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Funcionarios] })
  @ApiNestedQuery(FuncionariosFindManyArgs)
  async funcionariosItems(
    @common.Req() request: Request
  ): Promise<Funcionarios[]> {
    const args = plainToClass(FuncionariosFindManyArgs, request.query);
    return this.service.funcionariosItems({
      ...args,
      select: {
        cargo: true,
        createdAt: true,
        email: true,
        id: true,
        nome: true,
        salario: true,
        telefone: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Funcionarios })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async funcionarios(
    @common.Param() params: FuncionariosWhereUniqueInput
  ): Promise<Funcionarios | null> {
    const result = await this.service.funcionarios({
      where: params,
      select: {
        cargo: true,
        createdAt: true,
        email: true,
        id: true,
        nome: true,
        salario: true,
        telefone: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Funcionarios })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateFuncionarios(
    @common.Param() params: FuncionariosWhereUniqueInput,
    @common.Body() data: FuncionariosUpdateInput
  ): Promise<Funcionarios | null> {
    try {
      return await this.service.updateFuncionarios({
        where: params,
        data: data,
        select: {
          cargo: true,
          createdAt: true,
          email: true,
          id: true,
          nome: true,
          salario: true,
          telefone: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Funcionarios })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteFuncionarios(
    @common.Param() params: FuncionariosWhereUniqueInput
  ): Promise<Funcionarios | null> {
    try {
      return await this.service.deleteFuncionarios({
        where: params,
        select: {
          cargo: true,
          createdAt: true,
          email: true,
          id: true,
          nome: true,
          salario: true,
          telefone: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/acessosItems")
  @ApiNestedQuery(AcessosFindManyArgs)
  async findAcessosItems(
    @common.Req() request: Request,
    @common.Param() params: FuncionariosWhereUniqueInput
  ): Promise<Acessos[]> {
    const query = plainToClass(AcessosFindManyArgs, request.query);
    const results = await this.service.findAcessosItems(params.id, {
      ...query,
      select: {
        createdAt: true,
        dataHoraAcesso: true,

        funcionario: {
          select: {
            id: true,
          },
        },

        id: true,
        tipoAcesso: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/acessosItems")
  async connectAcessosItems(
    @common.Param() params: FuncionariosWhereUniqueInput,
    @common.Body() body: AcessosWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      acessosItems: {
        connect: body,
      },
    };
    await this.service.updateFuncionarios({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/acessosItems")
  async updateAcessosItems(
    @common.Param() params: FuncionariosWhereUniqueInput,
    @common.Body() body: AcessosWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      acessosItems: {
        set: body,
      },
    };
    await this.service.updateFuncionarios({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/acessosItems")
  async disconnectAcessosItems(
    @common.Param() params: FuncionariosWhereUniqueInput,
    @common.Body() body: AcessosWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      acessosItems: {
        disconnect: body,
      },
    };
    await this.service.updateFuncionarios({
      where: params,
      data,
      select: { id: true },
    });
  }
}
