/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Servicos } from "./Servicos";
import { ServicosCountArgs } from "./ServicosCountArgs";
import { ServicosFindManyArgs } from "./ServicosFindManyArgs";
import { ServicosFindUniqueArgs } from "./ServicosFindUniqueArgs";
import { DeleteServicosArgs } from "./DeleteServicosArgs";
import { ServicosService } from "../servicos.service";
@graphql.Resolver(() => Servicos)
export class ServicosResolverBase {
  constructor(protected readonly service: ServicosService) {}

  async _servicosItemsMeta(
    @graphql.Args() args: ServicosCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Servicos])
  async servicosItems(
    @graphql.Args() args: ServicosFindManyArgs
  ): Promise<Servicos[]> {
    return this.service.servicosItems(args);
  }

  @graphql.Query(() => Servicos, { nullable: true })
  async servicos(
    @graphql.Args() args: ServicosFindUniqueArgs
  ): Promise<Servicos | null> {
    const result = await this.service.servicos(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Servicos)
  async deleteServicos(
    @graphql.Args() args: DeleteServicosArgs
  ): Promise<Servicos | null> {
    try {
      return await this.service.deleteServicos(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
