/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  DisponibilidadeProfissionais as PrismaDisponibilidadeProfissionais,
} from "@prisma/client";

export class DisponibilidadeProfissionaisServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.DisponibilidadeProfissionaisCountArgs, "select">
  ): Promise<number> {
    return this.prisma.disponibilidadeProfissionais.count(args);
  }

  async disponibilidadeProfissionaisItems(
    args: Prisma.DisponibilidadeProfissionaisFindManyArgs
  ): Promise<PrismaDisponibilidadeProfissionais[]> {
    return this.prisma.disponibilidadeProfissionais.findMany(args);
  }
  async disponibilidadeProfissionais(
    args: Prisma.DisponibilidadeProfissionaisFindUniqueArgs
  ): Promise<PrismaDisponibilidadeProfissionais | null> {
    return this.prisma.disponibilidadeProfissionais.findUnique(args);
  }
  async createDisponibilidadeProfissionais(
    args: Prisma.DisponibilidadeProfissionaisCreateArgs
  ): Promise<PrismaDisponibilidadeProfissionais> {
    return this.prisma.disponibilidadeProfissionais.create(args);
  }
  async updateDisponibilidadeProfissionais(
    args: Prisma.DisponibilidadeProfissionaisUpdateArgs
  ): Promise<PrismaDisponibilidadeProfissionais> {
    return this.prisma.disponibilidadeProfissionais.update(args);
  }
  async deleteDisponibilidadeProfissionais(
    args: Prisma.DisponibilidadeProfissionaisDeleteArgs
  ): Promise<PrismaDisponibilidadeProfissionais> {
    return this.prisma.disponibilidadeProfissionais.delete(args);
  }
}
