/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Produtos } from "./Produtos";
import { ProdutosCountArgs } from "./ProdutosCountArgs";
import { ProdutosFindManyArgs } from "./ProdutosFindManyArgs";
import { ProdutosFindUniqueArgs } from "./ProdutosFindUniqueArgs";
import { DeleteProdutosArgs } from "./DeleteProdutosArgs";
import { ProdutosService } from "../produtos.service";
@graphql.Resolver(() => Produtos)
export class ProdutosResolverBase {
  constructor(protected readonly service: ProdutosService) {}

  async _produtosItemsMeta(
    @graphql.Args() args: ProdutosCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Produtos])
  async produtosItems(
    @graphql.Args() args: ProdutosFindManyArgs
  ): Promise<Produtos[]> {
    return this.service.produtosItems(args);
  }

  @graphql.Query(() => Produtos, { nullable: true })
  async produtos(
    @graphql.Args() args: ProdutosFindUniqueArgs
  ): Promise<Produtos | null> {
    const result = await this.service.produtos(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Produtos)
  async deleteProdutos(
    @graphql.Args() args: DeleteProdutosArgs
  ): Promise<Produtos | null> {
    try {
      return await this.service.deleteProdutos(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
