/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Acessos } from "./Acessos";
import { AcessosCountArgs } from "./AcessosCountArgs";
import { AcessosFindManyArgs } from "./AcessosFindManyArgs";
import { AcessosFindUniqueArgs } from "./AcessosFindUniqueArgs";
import { CreateAcessosArgs } from "./CreateAcessosArgs";
import { UpdateAcessosArgs } from "./UpdateAcessosArgs";
import { DeleteAcessosArgs } from "./DeleteAcessosArgs";
import { Funcionarios } from "../../funcionarios/base/Funcionarios";
import { AcessosService } from "../acessos.service";
@graphql.Resolver(() => Acessos)
export class AcessosResolverBase {
  constructor(protected readonly service: AcessosService) {}

  async _acessosItemsMeta(
    @graphql.Args() args: AcessosCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Acessos])
  async acessosItems(
    @graphql.Args() args: AcessosFindManyArgs
  ): Promise<Acessos[]> {
    return this.service.acessosItems(args);
  }

  @graphql.Query(() => Acessos, { nullable: true })
  async acessos(
    @graphql.Args() args: AcessosFindUniqueArgs
  ): Promise<Acessos | null> {
    const result = await this.service.acessos(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Acessos)
  async createAcessos(
    @graphql.Args() args: CreateAcessosArgs
  ): Promise<Acessos> {
    return await this.service.createAcessos({
      ...args,
      data: {
        ...args.data,

        funcionario: args.data.funcionario
          ? {
              connect: args.data.funcionario,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Acessos)
  async updateAcessos(
    @graphql.Args() args: UpdateAcessosArgs
  ): Promise<Acessos | null> {
    try {
      return await this.service.updateAcessos({
        ...args,
        data: {
          ...args.data,

          funcionario: args.data.funcionario
            ? {
                connect: args.data.funcionario,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Acessos)
  async deleteAcessos(
    @graphql.Args() args: DeleteAcessosArgs
  ): Promise<Acessos | null> {
    try {
      return await this.service.deleteAcessos(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Funcionarios, {
    nullable: true,
    name: "funcionario",
  })
  async getFuncionario(
    @graphql.Parent() parent: Acessos
  ): Promise<Funcionarios | null> {
    const result = await this.service.getFuncionario(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
