/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Acessos } from "./Acessos";
import { AcessosCountArgs } from "./AcessosCountArgs";
import { AcessosFindManyArgs } from "./AcessosFindManyArgs";
import { AcessosFindUniqueArgs } from "./AcessosFindUniqueArgs";
import { DeleteAcessosArgs } from "./DeleteAcessosArgs";
import { AcessosService } from "../acessos.service";
@graphql.Resolver(() => Acessos)
export class AcessosResolverBase {
  constructor(protected readonly service: AcessosService) {}

  async _acessosItemsMeta(
    @graphql.Args() args: AcessosCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Acessos])
  async acessosItems(
    @graphql.Args() args: AcessosFindManyArgs
  ): Promise<Acessos[]> {
    return this.service.acessosItems(args);
  }

  @graphql.Query(() => Acessos, { nullable: true })
  async acessos(
    @graphql.Args() args: AcessosFindUniqueArgs
  ): Promise<Acessos | null> {
    const result = await this.service.acessos(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Acessos)
  async deleteAcessos(
    @graphql.Args() args: DeleteAcessosArgs
  ): Promise<Acessos | null> {
    try {
      return await this.service.deleteAcessos(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
